import esbuild from "esbuild";
import process from "process";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

esbuild.build({
banner: {
js: banner,
},
entryPoints: ["main.ts"],
bundle: true,
external: [
"obsidian",
"electron",
],
format: "cjs",
target: "es2018",
logLevel: "info",
sourcemap: "inline",
treeShaking: true,
outfile: "main.js",
}).catch(() => process.exit(1));
